name: PyPI deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  pypi-deploy:
    name: Deploying Python Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        # setuptools_scm requires a non-shallow clone of the repository
        fetch-depth: 0

    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: "3.12"

    - name: Build SDist
      run: pipx run build --sdist --extra-index-url https://pypi.org/simple/

    - uses: pypa/gh-action-pypi-publish@v1.10.2
      with:
        repository-url: https://test.pypi.org/legacy/
